# Generated by Django 4.2.8 on 2026-01-19 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('phishing', 'Phishing'), ('identity_theft', 'Identity Theft'), ('online_fraud', 'Online Fraud'), ('cyberbullying', 'Cyberbullying'), ('hacking', 'Hacking'), ('ransomware', 'Ransomware'), ('data_breach', 'Data Breach'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('incident_date', models.DateTimeField(help_text='When the incident occurred')),
                ('incident_location', models.CharField(blank=True, max_length=255, null=True)),
                ('affected_system', models.CharField(blank=True, help_text='e.g., Email, Bank Account, Social Media', max_length=255, null=True)),
                ('encrypted_evidence_summary', models.TextField(blank=True, help_text='Encrypted summary of sensitive evidence', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('integrity_hash', models.CharField(help_text='SHA-256 hash for integrity', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Complaints',
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email Address'), ('url', 'URL/Website'), ('social_media', 'Social Media Account'), ('bank_details', 'Bank Details'), ('other', 'Other')], max_length=50)),
                ('value', models.TextField()),
                ('is_encrypted', models.BooleanField(default=False)),
                ('encrypted_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complaint_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('document', 'Document'), ('email', 'Email'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'mp4', 'mp3'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(help_text='SHA-256 hash of the file', max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Evidence Files',
                'db_table': 'evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal remarks not visible to complainant')),
                ('is_encrypted', models.BooleanField(default=False)),
                ('encrypted_content', models.TextField(blank=True, null=True)),
                ('remark_hash', models.CharField(help_text='SHA-256 hash for integrity', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Remarks',
                'db_table': 'remarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
