# Generated by Django 4.2.8 on 2026-01-19 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remark',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintattachment',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='remark',
            index=models.Index(fields=['complaint', '-created_at'], name='remarks_complai_d42704_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['complaint', '-uploaded_at'], name='evidence_complai_3fadcc_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['case_number'], name='complaints_case_nu_002e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', '-created_at'], name='complaints_status_dbbea4_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_officer', 'status'], name='complaints_assigne_a3bf96_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complainant', '-created_at'], name='complaints_complai_46bafa_idx'),
        ),
    ]
