# Generated by Django 4.2.8 on 2026-02-18 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Admin's reason for rejection or approval notes", null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='approval_status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved the complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('near_to_close', 'Near to Close'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_complaint', 'New Complaint'), ('complaint_approved', 'Complaint Approved'), ('complaint_rejected', 'Complaint Rejected'), ('urgent_case', 'Urgent Case')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='complaints.complaint')),
            ],
            options={
                'db_table': 'admin_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'is_read', '-created_at'], name='admin_notif_admin_i_a96e2d_idx')],
            },
        ),
    ]
