# Generated by Django 4.2.8 on 2026-02-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_admin_notes_complaint_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='affected_system',
            field=models.CharField(blank=True, help_text='e.g., Email, Bank Account, Social Media', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='approval_status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=17),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='case_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('phishing', 'Phishing'), ('identity_theft', 'Identity Theft'), ('online_fraud', 'Online Fraud'), ('cyberbullying', 'Cyberbullying'), ('hacking', 'Hacking'), ('ransomware', 'Ransomware'), ('data_breach', 'Data Breach'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='incident_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('near_to_close', 'Near to Close'), ('closed', 'Closed')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='complaintattachment',
            name='attachment_type',
            field=models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email Address'), ('url', 'URL/Website'), ('social_media', 'Social Media Account'), ('bank_details', 'Bank Details'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file_type',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('document', 'Document'), ('email', 'Email'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=20),
        ),
    ]
