# Generated by Django 4.2.8 on 2026-01-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=255)),
                ('investigation_summary', models.TextField()),
                ('findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('report_hash', models.CharField(help_text='SHA-256 hash for integrity', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Case Reports',
                'db_table': 'case_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_complaints', models.IntegerField(default=0)),
                ('pending_complaints', models.IntegerField(default=0)),
                ('in_progress_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('closed_complaints', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_officers', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Case Statistics',
                'db_table': 'case_statistics',
            },
        ),
        migrations.CreateModel(
            name='CaseWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned to Officer'), ('in_investigation', 'Under Investigation'), ('evidence_collected', 'Evidence Collected'), ('analysis_done', 'Analysis Completed'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('action_hash', models.CharField(help_text='SHA-256 hash for integrity', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Case Workflows',
                'db_table': 'case_workflow',
                'ordering': ['-created_at'],
            },
        ),
    ]
