# Generated by Django 4.2.8 on 2026-01-19 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseworkflow',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casereport',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='casereport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='caseworkflow',
            index=models.Index(fields=['complaint', '-created_at'], name='case_workfl_complai_2fbef6_idx'),
        ),
    ]
