# Generated by Django 4.2.8 on 2026-02-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='report_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='caseworkflow',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned to Officer'), ('in_investigation', 'Under Investigation'), ('evidence_collected', 'Evidence Collected'), ('analysis_done', 'Analysis Completed'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=25),
        ),
    ]
