# Generated by Django 4.2.8 on 2026-02-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_needs_reset',
            field=models.BooleanField(default=False, help_text='User must reset password to meet CERT-IN 16-21 character requirement'),
        ),
    ]
