# Generated by Django 4.2.8 on 2026-02-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_password_reset_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create_complaint', 'Create Complaint'), ('update_complaint', 'Update Complaint'), ('view_complaint', 'View Complaint'), ('assign_case', 'Assign Case'), ('add_remark', 'Add Remark'), ('upload_evidence', 'Upload Evidence'), ('export_report', 'Export Report'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='badge_number',
            field=models.CharField(blank=True, help_text='For officers: Badge number', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, help_text='For officers: Department name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('officer', 'Cybercrime Officer'), ('admin', 'Administrator')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='sessionmanagement',
            name='session_token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
