# Generated by Django 4.2.8 on 2026-02-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_otp',
            field=models.CharField(blank=True, help_text='6-digit OTP for password reset', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_otp_expiry',
            field=models.DateTimeField(blank=True, help_text='OTP expiry timestamp (15 minutes)', null=True),
        ),
    ]
